name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web bundle
        run: npm run web:build

      - name: Build Windows installer (electron-builder)
        run: npx electron-builder --win --x64
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: moodbites-windows-installer
          path: release/**
          if-no-files-found: error
